export const WS_FEED_CONNECTION_START: "WS_FEED_CONNECTION_START" = "WS_FEED_CONNECTION_START";
export const WS_FEED_CONNECTION_SUCCESS: "WS_FEED_CONNECTION_SUCCESS" = "WS_FEED_CONNECTION_SUCCESS";
export const WS_FEED_CONNECTION_ERROR: "WS_FEED_CONNECTION_ERROR" = "WS_FEED_CONNECTION_ERROR";
export const WS_FEED_CONNECTION_CLOSED: "WS_FEED_CONNECTION_CLOSED" = "WS_FEED_CONNECTION_CLOSED";
export const WS_FEED_GET_MESSAGE: "WS_FEED_GET_MESSAGE" = "WS_FEED_GET_MESSAGE";
export const WS_FEED_SEND_MESSAGE: "WS_FEED_SEND_MESSAGE" = "WS_FEED_SEND_MESSAGE";
export const SET_CURRENT_WS_FEED: "SET_CURRENT_WS_FEED" = "SET_CURRENT_WS_FEED";
export const REMOVE_CURRENT_WS_FEED: "REMOVE_CURRENT_WS_FEED" = "REMOVE_CURRENT_WS_FEED";
