export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const DELETE_ALL: "DELETE_ALL" = "DELETE_ALL";
export const REPLACE_FILLING: "REPLACE_FILLING" = "REPLACE_FILLING";
export const CREATE_ORDER: "CREATE_ORDER" = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS" = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED" = "CREATE_ORDER_FAILED";
